user:
  length:
    max_name: 50
    min_pass: 6
    max_email: 50
category:
  length:
    max_name: 50
course:
  length:
    max_name: 50
lession:
  length:
    max_name: 50
image:
  size: 400
  capacity: 5
